#include <stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int fibSum(int n) {
	
	int sum = 0;
	int cur = 2;
	int past = 1;
	int aux = 0;

	while (cur < n) {
		if (cur % 2 == 0) {
			sum += cur;
		}
		aux = cur;
		cur = past + cur;
		past = aux;
	}

	return sum;
}

int main() {

	int sum = fibSum(4000000);

	printf("Sum fib: %d", sum);

	return 0;
}
